ALTER TABLE categories ADD COLUMN is_hidden BOOLEAN DEFAULT FALSE;
ALTER TABLE products ADD COLUMN is_hidden BOOLEAN DEFAULT FALSE;
ALTER TABLE stocks ADD COLUMN is_hidden BOOLEAN DEFAULT FALSE;
ALTER TABLE availabilities ADD COLUMN is_hidden BOOLEAN DEFAULT FALSE; 